version: '3'
services:
  mongodb:
    image: bitnami/mongodb:4.4
    environment:
      MONGODB_ROOT_PASSWORD: password
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: password
      MONGODB_DATABASE: nest
    ports:
      - "27017:27017"